# Generated by Django 4.2 on 2023-05-08 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0005_alter_pedido_imagen_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='Usuario_pedido',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
