# Generated by Django 4.2 on 2023-05-08 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0006_pedido_usuario_pedido'),
    ]

    operations = [
        migrations.CreateModel(
            name='votos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Votos', models.IntegerField()),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Ultimo_voto', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
