# Generated by Django 4.2 on 2023-05-09 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0008_votos_usuario_voto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='Usuario_pedido',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='votos',
            name='Usuario_voto',
            field=models.CharField(max_length=50),
        ),
    ]
