# Generated by Django 4.2 on 2023-05-09 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0009_alter_pedido_usuario_pedido_alter_votos_usuario_voto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='votos',
            options={'verbose_name': 'Voto', 'verbose_name_plural': 'Votos'},
        ),
    ]
