# Generated by Django 4.2 on 2023-05-09 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0010_alter_votos_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='votos',
            old_name='Usuario_voto',
            new_name='Usuario_Nombre',
        ),
        migrations.AddField(
            model_name='votos',
            name='Usuario_id',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
