# Generated by Django 4.2 on 2023-05-09 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0011_rename_usuario_voto_votos_usuario_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='Usuario_id',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
