# Generated by Django 4.2 on 2023-04-27 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Juego', models.CharField(max_length=50)),
                ('Seccion', models.CharField(max_length=50)),
                ('Precio', models.IntegerField()),
            ],
        ),
    ]
