# Generated by Django 4.1.7 on 2023-05-03 21:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Registros', '0002_registro_tiempo'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='Created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
