# Generated by Django 4.2 on 2023-05-09 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registros', '0004_registro_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='Usuario',
            field=models.CharField(max_length=50),
        ),
    ]
