# Generated by Django 4.1.7 on 2023-05-09 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registros', '0006_registro_id_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='Img',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
