# Generated by Django 4.1.7 on 2023-05-09 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registros', '0007_registro_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='numero_de_veces_alquilado',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
