# Generated by Django 4.1.7 on 2023-05-09 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registros', '0008_registro_numero_de_veces_alquilado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registro',
            old_name='numero_de_veces_alquilado',
            new_name='alquiladas',
        ),
    ]
