# Generated by Django 4.1.7 on 2023-05-10 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registros', '0009_rename_numero_de_veces_alquilado_registro_alquiladas'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
