# Generated by Django 4.1.7 on 2023-04-26 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Juegos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='limite_alquiler',
            name='Dias_Meses',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
