# Generated by Django 4.1.7 on 2023-05-03 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Juegos', '0005_remove_juego_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seccion_juego',
            name='Created',
        ),
        migrations.RemoveField(
            model_name='seccion_juego',
            name='Updated',
        ),
    ]
